version: "3"
services:
  lavalink:
    build:
      context: ./lavalink
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    networks:
      ds_net:
        aliases:
          - lavalink-server

  purgador:
    build:
      context: ./purgador
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - lavalink
    restart: always
    networks:
      ds_net:
        aliases:
          - purgador-server

networks:
  ds_net:
    ipam:
      driver: default
